---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay
  labels:
    app: quay
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      containers:

      - name: pgsql
        image: registry.redhat.io/rhel8/postgresql-13:1-109
        env:
        - name: POSTGRESQL_USER
          value: quay
        - name: POSTGRESQL_DATABASE
          value: quay
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: password
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgsql-secret
              key: password
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: pgsql-db
        ports:
        - name: pgsql
          containerPort: 5432
          hostPort: 5432

      - name: redis
        image: registry.redhat.io/rhel8/redis-6:1-110
        ports:
        - name: redis
          containerPort: 6379
          hostPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password

      - name: quay
        image: registry.redhat.io/quay/quay-rhel8:v3.11.1
        ports:
        - name: web
          containerPort: 8443
          hostPort: 443
        volumeMounts:
        - mountPath: /conf/stack/config.yaml
          subPath: config.yaml
          name: quay-config
        - mountPath: /conf/stack/ssl.key
          subPath: ssl.key
          name: quay-tls
        - mountPath: /conf/stack/ssl.cert
          subPath: ssl.cert
          name: quay-tls
        - mountPath: /datastorage
          name: quay-storage

      volumes:
      - name: pgsql-db
        persistentVolumeClaim:
          claimName: pgsql-db

      - name: quay-storage
        persistentVolumeClaim:
          claimName: quay-storage

      - name: quay-config
        secret:
          secretName: quay-config
          items:
          - key: quay.config
            path: config.yaml

      - name: quay-tls
        secret:
          secretName: quay-tls
          items:
          - key: tls.key
            path: ssl.key
          - key: tls.crt
            path: ssl.cert
